export class ApplicationForm {
    id:any;
    applicantName:any;
    applicantMail:any;
    patientName:any;
    address:any;
    city:any;
    district:any;
    state:any;
    mobile:any;
    status:any;
    imageId:any;
    waitingWith:any;
    approvedBy:any;
    emergency:any;
    deliveryinitiated:any;
    appliedOn:any;
    approvedOn:any;
    lastUpdate:any;
}
